"""Parity checks against a frozen source-generated Frontier fixture.

The fixture was generated by the read-only 2026-08-23 academic wrappers and
contains no source import or private filesystem path.  These tests therefore
exercise the extracted package independently while checking fit state,
marginal paths, Kalman state, dependent uniforms, and portfolio rejoin.
"""

from __future__ import annotations

from importlib import resources

import numpy as np
import pandas as pd

from simfolio_forecasting_methodology.models.asset_level.frontier import (
    FRONTIER_MODEL_ID,
    HistoricalFrontierModel,
    _historical_rebalance_dates,
)
from simfolio_forecasting_methodology.models.numerical.bdes_fastmap import (
    FRONTIER_CANDIDATE,
    FRONTIER_DEPENDENCE_ID,
    FRONTIER_MARGINAL_ID,
    deterministic_seed,
    fit_bdes_fastmap,
    simulate_fastmap_marginal,
    simulate_full_mcmc_sv_bdes_log_paths_serial_numba,
)
from simfolio_forecasting_methodology.models.numerical.dynamic_gaussian import (
    fit_dynamic_gaussian_factor_model,
    kalman_terminal_posterior,
    map_uniforms_to_marginal_paths,
    rebalanced_portfolio_log_paths,
    simulate_future_gaussian_uniforms,
)
from simfolio_forecasting_methodology.runner import ForecastContext, PortfolioPolicy, TrainingData


def _load(name: str = "source_reference.npz") -> dict[str, np.ndarray]:
    fixture = (
        resources.files("simfolio_forecasting_methodology")
        .joinpath("resources", "test_fixtures", "frontier", name)
    )
    with fixture.open("rb") as handle, np.load(handle, allow_pickle=False) as data:
        return {name: np.asarray(data[name]) for name in data.files}


def test_fastmap_fit_and_marginal_match_source_fixture() -> None:
    fixture = _load()
    tickers = ("ALPHA", "BETA", "GAMMA", "DELTA")
    origin = str(pd.Timestamp(fixture["training_dates"][-1]).date())
    for asset, ticker in enumerate(tickers):
        fit = fit_bdes_fastmap(fixture["asset_log_returns"][:, asset], FRONTIER_CANDIDATE)
        np.testing.assert_allclose(fit["posterior_center"], fixture["posterior_centers"][asset], rtol=0.0, atol=2e-12)
        np.testing.assert_allclose(fit["bdes_multiscale_vol"]["b"], fixture["bdes_coefficients"][asset], rtol=0.0, atol=2e-12)
        seed = deterministic_seed("asset_level_current_engine", ticker, origin, FRONTIER_MARGINAL_ID, 8, 16)
        paths = simulate_fastmap_marginal(fit, 16, 8, seed)
        np.testing.assert_allclose(paths, fixture["marginal_paths"][:, :, asset], rtol=0.0, atol=2e-12)


def test_factor_kalman_uniform_and_rejoin_match_source_fixture() -> None:
    fixture = _load()
    model = fit_dynamic_gaussian_factor_model(fixture["asset_log_returns"])
    for key, expected in (
        ("mean", fixture["factor_mean"]),
        ("loading", fixture["factor_loading"]),
        ("residual_variance", fixture["factor_residual_variance"]),
        ("phi", fixture["factor_phi"]),
        ("innovation_variance", fixture["factor_innovation_variance"]),
        ("initial_variance", fixture["factor_initial_variance"]),
    ):
        np.testing.assert_allclose(model[key], expected, rtol=0.0, atol=2e-12)
    state, covariance = kalman_terminal_posterior(model)
    np.testing.assert_allclose(state, fixture["kalman_state"], rtol=0.0, atol=2e-12)
    np.testing.assert_allclose(covariance, fixture["kalman_covariance"], rtol=0.0, atol=2e-12)
    seed = deterministic_seed("copula_alternatives", FRONTIER_DEPENDENCE_ID, "2026-05-13", 8, 16)
    uniforms = simulate_future_gaussian_uniforms(model, 16, 8, np.random.default_rng(seed))
    np.testing.assert_allclose(uniforms, fixture["uniforms"], rtol=0.0, atol=2e-12)
    mapped = map_uniforms_to_marginal_paths(fixture["marginal_paths"], uniforms)
    full_dates = pd.DatetimeIndex(fixture["training_dates"]).append(pd.DatetimeIndex(fixture["future_dates"]))
    dates = _historical_rebalance_dates(full_dates, "monthly")
    mask = np.asarray([date in dates for date in pd.DatetimeIndex(fixture["future_dates"])], dtype=bool)
    rejoined = rebalanced_portfolio_log_paths(mapped, fixture["weights"], mask)
    np.testing.assert_allclose(rejoined, fixture["rejoined_log_returns"], rtol=0.0, atol=2e-12)


def test_named_serial_bdes_kernel_preserves_measurement_clamp() -> None:
    output = simulate_full_mcmc_sv_bdes_log_paths_serial_numba(
        np.ones((1, 1), dtype=np.float64),
        np.zeros((1, 1), dtype=np.float64),
        np.zeros(1, dtype=np.float64),
        np.ones(1, dtype=np.float64),
        np.zeros(1, dtype=np.float64),
        np.zeros(1, dtype=np.float64),
        np.zeros(1, dtype=np.float64),
        np.zeros(1, dtype=np.float64),
        np.ones((1, 1), dtype=np.float64),
        np.zeros((1, 1), dtype=np.float64),
        np.zeros(1, dtype=np.float64),
        np.ones(1, dtype=np.float64),
        np.ones(1, dtype=np.float64),
        np.ones(1, dtype=np.float64) * 100.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        -200.0,
        200.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        1.0,
        False,
        False,
        False,
        0,
        False,
        False,
    )
    np.testing.assert_allclose(output, np.asarray([[np.exp(9.0) / 100.0]]), rtol=0.0, atol=1e-12)


def test_source_rejoin_fixture_exercises_calendar_turnover() -> None:
    fixture = _load("rejoin_calendar_reference.npz")
    full_dates = pd.DatetimeIndex(fixture["historical_dates"]).append(
        pd.DatetimeIndex(fixture["future_dates"])
    )
    future_dates = pd.DatetimeIndex(fixture["future_dates"])
    for policy in ("none", "monthly", "quarterly", "annually"):
        dates = _historical_rebalance_dates(full_dates, policy)
        mask = np.asarray([date in dates for date in future_dates], dtype=bool)
        np.testing.assert_array_equal(mask, fixture[f"mask_{policy}"])
        output = rebalanced_portfolio_log_paths(
            fixture["log_paths"],
            fixture["weights"],
            mask,
            cost_per_turnover_bps=float(fixture["cost_bps"]),
        )
        np.testing.assert_allclose(
            output,
            fixture[f"output_{policy}"],
            rtol=0.0,
            atol=2e-14,
        )


def test_public_model_requires_real_calendar_and_returns_frontier_shape() -> None:
    fixture = _load()
    train = TrainingData(
        portfolio_log_returns=np.einsum("ij,j->i", fixture["asset_log_returns"], fixture["weights"]),
        asset_log_returns=fixture["asset_log_returns"],
        policy=PortfolioPolicy(("ALPHA", "BETA", "GAMMA", "DELTA"), tuple(fixture["weights"]), "monthly"),
        training_dates=fixture["training_dates"],
    )
    context = ForecastContext(
        model_id=FRONTIER_MODEL_ID,
        portfolio_id="fixture",
        origin_label="fixture-origin",
        horizon_days=8,
        simulations=16,
        seed=123,
        future_dates=fixture["future_dates"],
        origin_date="2026-05-13",
    )
    result = HistoricalFrontierModel().simulate_daily_log_returns(train, context)
    assert result.shape == (16, 8)
    assert np.isfinite(result).all()
    np.testing.assert_allclose(result, fixture["rejoined_log_returns"], rtol=0.0, atol=2e-12)
    with np.testing.assert_raises(ValueError):
        HistoricalFrontierModel().simulate_daily_log_returns(train, ForecastContext(**{**context.__dict__, "origin_date": None}))
